FEATURE_LEVEL = 'test'

if FEATURE_LEVEL == 'test'
  FEATURE_LIMIT_TO_CLOUDFLARE = false
  FEATURE_SHOW_GENERAL_ELECTION_CARTOGRAMS = true
  FEATURE_SHOW_ELECTION_TIME_SERIES = true
else
  FEATURE_LIMIT_TO_CLOUDFLARE = true
  FEATURE_SHOW_GENERAL_ELECTION_CARTOGRAMS = false
  FEATURE_SHOW_ELECTION_TIME_SERIES = false
end